name: rich-tab
base: core22
adopt-info: rtab
summary: Convert json, yaml or csv into tables using the rich library
license: MIT
description: |
  A simple formatting cli that converts json, yaml or csv into tables using the rich library

grade: stable
confinement: strict

apps:
  rtab:
    command: bin/rtab.wrapper
    aliases: [rtab]
    plugs:
      - home

parts:
  rtab-wrapper:
    plugin: dump
    source: bin
    organize:
      rtab.wrapper: bin/rtab.wrapper

  rtab:
    plugin: python
    build-packages:
      - python3-pip
    source: .
    stage-packages:
      - git
    override-build: |
      set -e -u -x
      git rev-parse --short HEAD > rtab/.repo-info
      pip install setuptools-git-versioning
      craftctl default
      # set version
      VERSION="$(setuptools-git-versioning)"
      echo "Version: ${VERSION}"
      craftctl set version=${VERSION}
