name: rich-tab
base: core22
adopt-info: rtab
summary: Convert json, yaml or csv into tables using the rich library
license: MIT
description: |
  A simple formatting cli that converts json, yaml or csv into tables using the rich library

grade: devel
confinement: strict

apps:
  rtab:
    command: bin/rtab.wrapper
    aliases: [rtab]
    plugs:
      - home

parts:
  rtab-wrapper:
    plugin: dump
    source: bin
    organize:
      rtab.wrapper: bin/rtab.wrapper

  rtab:
    plugin: python
    build-packages:
      - python3-wheel
      - python3-pip
      - python3-setuptools-scm
    source: .
    stage-packages:
      - git
    override-build: |
      craftctl default
      set -e
      # set version
      VERSION=$(python3 setup.py --version)
      echo "Version: ${VERSION}"
      craftctl set version=${VERSION}
